### ISSUE TITLE
workon command does not work with cmd.exe shell

### ISSUE THREAD

**Issue by FlorianWolters** [davidmarble/virtualenvwrapper-win#110] opened 2020-04-03 11:29 UTC
Step(s) to reproduce:

    mkvirtualenv foo
    workon foo

Output: **none**

The `setprojectdir .` command outputs the following:

    ERROR: A virtualenv must be activated.

    Pass in a full or relative path to the project directory.
    If the directory doesn't exist, it will be created:

        setprojectdir PATH

Environment:

- OS: Windows v10.0.18363.752 x64
- Python v2.7.17 (installed via pyenv-win)
- virtualenv v20.0.25
- virtualenvwrapper-win v1.2.6
- Using `cmd.exe` shell.

**Comment by thebjorn** [comment] 2020-04-03 12:29
I can't reproduce this without pyenv-win.  I'm closing this since I'm sure that if #109 is resolved then this will be as well.

**Closed by thebjorn** 2020-04-03 12:29 UTC
